### ISSUE TITLE
Add colorWithPatternImage support

### ISSUE THREAD

**Issue by jrapoport** [appwilldev/AWLThemeManager#14]
Now if you specify as color as “#[ImageName]” it will search for the
“Foo” image using the usual methods & if found, return a color using
that image as a pattern. To change the alpha, use
“#[ImageName],[Alpha]” e.g. #Foo,0.3

see 63c7e3f

**Comment by Neeeo** [comment]
merged. [e4e913e](https://github.com/appwilldev/AWLThemeManager/commit/e4e913e633a5037de84010271fbd8db256a56b39)

**Comment by Neeeo** [comment]
change method:
`- (UIColor*)colorFromString:(NSString*)colorValue forTheme:(NSString *)themeName`
to
`- (UIColor*)colorFromString:(NSString*)colorValue`

so pattern image can be changed from theme inheritance.
