### ISSUE TITLE
Support keyed images

### ISSUE THREAD

**Issue by jrapoport** [appwilldev/AWLThemeManager#9]
Currently you can override image "foo" (foo.png) in Bundle A with foo.png in Bundle B.

However, sometimes you need to override image "foo" (foo.png) in Bundle A with quack.png in Bundle B. Basically you want to request imageNamed: "Foo", but have the theme swap that out for "Quack" via the plist, and then try to find imageNamed: "Quack" instead.

**Comment by jrapoport** [comment]
p.s. this also makes life a lot easier if you are using complied xcasset files in the bundle.

**Comment by Neeeo** [comment]
PR #10
